baseURL = 'https://godfrey.nl/'
languageCode = 'en-us'
title = '@_tristangodfrey'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
[markup.goldmark.parser]
  [markup.goldmark.parser.attribute]
    block = true
    title = true

[module]
  [[module.mounts]]
    source = 'content/Blog/Posts'
    target = 'content/posts'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]

[params]
  maintenance_mode = false
  description = "Musings about software engineering, love, and life."
  text_color = "mid-gray"
  author = "Tristan"
  favicon = ""
  site_logo = ""
  read_more_copy = "Read more"
  body_classes = "avenir bg-near-white"
  custom_css = ["css/custom.css"]

  [params.ananke.social.x-twitter]
    username = "_tristangodfrey"

  [params.ananke.social.follow]
    networks = ["x-twitter"]

summaryLength = 20

[frontmatter]
  title = ["title", ":filename"]
